version: '3.9'

services:
  db:
    image: postgres:alpine3.17
    container_name: postgres-db
    volumes:
      # - postgres-db:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456

  pgadmin:
    image: dpage/pgadmin4:6.19
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - db
      
# volumes:
  # postgres-db:
    # external: true (para volumen existente)